<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="Content-Style-Type" content="text/css">
  <title></title>
  <meta name="Generator" content="Cocoa HTML Writer">
  <meta name="CocoaVersion" content="2022.3">
  <style type="text/css">
    p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica}
    p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px}
  </style>
</head>
<body>
<p class="p1">name: Bitcoin order App</p>
<p class="p1">on:</p>
<p class="p1"><span class="Apple-converted-space">  </span>push:</p>
<p class="p1"><span class="Apple-converted-space">    </span>branches:</p>
<p class="p1"><span class="Apple-converted-space">      </span>- githubcicd</p>
<p class="p1">jobs:</p>
<p class="p1"><span class="Apple-converted-space">  </span>ci:</p>
<p class="p1"><span class="Apple-converted-space">    </span>runs-on: ubuntu-latest</p>
<p class="p2"><br></p>
<p class="p1"><span class="Apple-converted-space">    </span>strategy:</p>
<p class="p1"><span class="Apple-converted-space">      </span>matrix:</p>
<p class="p1"><span class="Apple-converted-space">        </span>node-version: [16.x]</p>
<p class="p2"><br></p>
<p class="p1"><span class="Apple-converted-space">    </span>steps:</p>
<p class="p1"><span class="Apple-converted-space">      </span>- uses: actions/checkout@v2</p>
<p class="p1"><span class="Apple-converted-space">      </span>- uses: browser-actions/setup-chrome@latest</p>
<p class="p1"><span class="Apple-converted-space">      </span>- name: Use Node.js ${{ matrix.node-version }}</p>
<p class="p1"><span class="Apple-converted-space">        </span>uses: actions/setup-node@v1</p>
<p class="p1"><span class="Apple-converted-space">        </span>with:</p>
<p class="p1"><span class="Apple-converted-space">          </span>node-version: ${{ matrix.node-version }}</p>
<p class="p2"><br></p>
<p class="p1"><span class="Apple-converted-space">      </span>- name: Cache node modules</p>
<p class="p1"><span class="Apple-converted-space">        </span>id: cache-nodemodules</p>
<p class="p1"><span class="Apple-converted-space">        </span>uses: actions/cache@v2</p>
<p class="p1"><span class="Apple-converted-space">        </span>env:</p>
<p class="p1"><span class="Apple-converted-space">          </span>cache-name: cache-node-modules</p>
<p class="p1"><span class="Apple-converted-space">        </span>with:</p>
<p class="p1"><span class="Apple-converted-space">          </span># caching node_modules</p>
<p class="p1"><span class="Apple-converted-space">          </span>path: node_modules</p>
<p class="p1"><span class="Apple-converted-space">          </span>key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}</p>
<p class="p1"><span class="Apple-converted-space">          </span>restore-keys: |</p>
<p class="p1"><span class="Apple-converted-space">            </span>${{ runner.os }}-build-${{ env.cache-name }}-</p>
<p class="p1"><span class="Apple-converted-space">            </span>${{ runner.os }}-build-</p>
<p class="p1"><span class="Apple-converted-space">            </span>${{ runner.os }}-</p>
<p class="p1"><span class="Apple-converted-space">      </span>- name: Install Dependencies</p>
<p class="p1"><span class="Apple-converted-space">        </span>if: steps.cache-nodemodules.outputs.cache-hit != 'true'</p>
<p class="p1"><span class="Apple-converted-space">        </span>run: |</p>
<p class="p1"><span class="Apple-converted-space">          </span>npm ci --force</p>
<p class="p1"><span class="Apple-converted-space">      </span>- name: Build</p>
<p class="p1"><span class="Apple-converted-space">        </span>run: |</p>
<p class="p1"><span class="Apple-converted-space">          </span>npm run build --force</p>
<p class="p1"><span class="Apple-converted-space">      </span>- name: Lint</p>
<p class="p1"><span class="Apple-converted-space">        </span>run: |</p>
<p class="p1"><span class="Apple-converted-space">          </span>npm run lint</p>
<p class="p1"><span class="Apple-converted-space">      </span>- name: Update types to latest</p>
<p class="p1"><span class="Apple-converted-space">        </span>run: |</p>
<p class="p1"><span class="Apple-converted-space">          </span>npm install --save-dev @types/node@latest --force</p>
<p class="p1"><span class="Apple-converted-space">      </span>- name: Test</p>
<p class="p1"><span class="Apple-converted-space">        </span>run: |</p>
<p class="p1"><span class="Apple-converted-space">          </span>npm run test</p>
<p class="p1"><span class="Apple-converted-space">      </span>- name: Conventional Changelog Action</p>
<p class="p1"><span class="Apple-converted-space">        </span>id: changelog</p>
<p class="p1"><span class="Apple-converted-space">        </span>uses: TriPSs/conventional-changelog-action@v3</p>
<p class="p1"><span class="Apple-converted-space">        </span>with:</p>
<p class="p1"><span class="Apple-converted-space">          </span>github-token: ${{ secrets.WORKSHOP6_GITHUB_TOKEN }}</p>
<p class="p1"><span class="Apple-converted-space">          </span>output-file: "false"</p>
<p class="p2"><br></p>
<p class="p1"><span class="Apple-converted-space">      </span>- name: Create Release</p>
<p class="p1"><span class="Apple-converted-space">        </span>uses: actions/create-release@v1</p>
<p class="p1"><span class="Apple-converted-space">        </span>if: ${{ steps.changelog.outputs.skipped == 'false' }}</p>
<p class="p1"><span class="Apple-converted-space">        </span>env:</p>
<p class="p1"><span class="Apple-converted-space">          </span>GITHUB_TOKEN: ${{ secrets.WORKSHOP6_GITHUB_TOKEN }}</p>
<p class="p1"><span class="Apple-converted-space">        </span>with:</p>
<p class="p1"><span class="Apple-converted-space">          </span>tag_name: ${{ steps.changelog.outputs.tag }}</p>
<p class="p1"><span class="Apple-converted-space">          </span>release_name: ${{ steps.changelog.outputs.tag }}</p>
<p class="p1"><span class="Apple-converted-space">          </span>body: ${{ steps.changelog.outputs.clean_changelog }}</p>
<p class="p1"><span class="Apple-converted-space">      </span>- name: Deploy</p>
<p class="p1"><span class="Apple-converted-space">        </span>run: |</p>
<p class="p1"><span class="Apple-converted-space">          </span>npm run deploy</p>
</body>
</html>
